
import localFont from "next/font/local";
import Navbar from "../components/Navbar"
import "./globals.css";
import SearchBar from "../components/SearchBar";
import Billboard from "../components/Billboard";
import { ClerkProvider } from "@clerk/nextjs";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <ClerkProvider afterSignOutUrl="/">
      <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        <SearchBar/>
         <Billboard/>
      </body>
    </html>
    </ClerkProvider>
  );
}
